#ifndef APP_CONFIG_H
#define APP_CONFIG_H
#define BATTERY_MONITOR_SAMPLE_PERIOD_MS 1000U
#define BATTERY_FULL_VOLTAGE_V 12.60f
#define BATTERY_EMPTY_VOLTAGE_V 9.60f
#define BATTERY_LOW_SOC_PERCENT 20.0f
#define BATTERY_MAX_CURRENT_A 8.00f
#define BATTERY_MAX_TEMP_C 50.0f
#endif
